# Generated by Django 4.0.5 on 2023-07-26 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('ciudad', models.CharField(default='', max_length=100)),
                ('pais', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('f_fabricacion', models.DateField(blank=True, null=True)),
                ('p_costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('p_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('laboratorio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='laboratorios.laboratorio')),
            ],
        ),
        migrations.CreateModel(
            name='Directorgeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('especialidad', models.CharField(default='', max_length=100)),
                ('laboratorio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='laboratorios.laboratorio')),
            ],
        ),
    ]
